---
apiVersion: v1
kind: Namespace
metadata:
  name: service-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: black-dep
  namespace: service-demo
  labels:
    app: ingress-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-black
  template:
    metadata:
      labels:
        app: ingress-black
        color: black
    spec:
      containers:
        - name: servicedemo
          image: ascosmo/servicedemo:1.0
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: IMAGE_COLOR
              value: black
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: POD_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: requests.cpu
            - name: POD_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: limits.cpu
            - name: POD_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: requests.memory
            - name: POD_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: limits.memory
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-dep
  namespace: service-demo
  labels:
    app: ingress-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ingress-red
  template:
    metadata:
      labels:
        app: ingress-red
        color: black
    spec:
      containers:
        - name: servicedemo
          image: ascosmo/servicedemo:1.0
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: IMAGE_COLOR
              value: red
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: POD_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: requests.cpu
            - name: POD_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: limits.cpu
            - name: POD_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: requests.memory
            - name: POD_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: limits.memory
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-dep
  namespace: service-demo
  labels:
    app: ingress-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ingress-yellow
  template:
    metadata:
      labels:
        app: ingress-yellow
        color: yellow
    spec:
      containers:
        - name: servicedemo
          image: ascosmo/servicedemo:1.0
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: IMAGE_COLOR
              value: yellow
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: POD_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: requests.cpu
            - name: POD_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: limits.cpu
            - name: POD_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: requests.memory
            - name: POD_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: servicedemo
                  resource: limits.memory
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
---
apiVersion: v1
kind: Service
metadata:
  name: black-svc
  namespace: service-demo
  labels:
    app: ingress-demo
spec:
  ports:
    - port: 8100
      targetPort: 80
      name: web
  selector:
    app: ingress-black
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yellow-svc
  namespace: service-demo
  labels:
    app: ingress-demo
spec:
  ports:
    - port: 8100
      targetPort: 80
      name: web
  selector:
    app: ingress-yellow
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: red-svc
  namespace: service-demo
  labels:
    app: ingress-demo
spec:
  ports:
    - port: 8100
      targetPort: 80
      name: web
  selector:
    app: ingress-red
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colors-ingress
  namespace: service-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: servicedemo.172.16.24.128.nip.io
      http:
        paths:
          - path: /black/(.*)
            pathType: Prefix
            backend:
              service:
                name: black-svc
                port:
                  number: 8100
          - path: /red/(.*)
            pathType: Prefix
            backend:
              service:
                name: red-svc
                port:
                  number: 8100
          - path: /yellow/(.*)
            pathType: Prefix
            backend:
              service:
                name: yellow-svc
                port:
                  number: 8100
